{% set name = "aws-c-http" %}
{% set version = "0.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4ccbdd33c798b590288330dec9e93abe2ff6cfb198b7a4db036c9d362f2e6506

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-c-http", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake >=3.9
    - ninja-base
  host:
    - aws-c-cal 0.9.14
    - aws-c-common 0.14.0
    - aws-c-compression 0.3.2
    - aws-c-io 0.26.3

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-http${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/http/http.h  # [unix]
    - if not exist %LIBRARY_INC%\aws\http\http.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\aws-c-http.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-http
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the HTTP protocol
  description: |
    C99 implementation of the HTTP/1.1 and HTTP/2 specifications
  doc_url: https://github.com/awslabs/aws-c-http
  dev_url: https://github.com/awslabs/aws-c-http

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
